// <auto-generated />
using System;
using MaxshoesBack.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaxshoesBack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210218082951_addContact")]
    partial class addContact
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaxshoesBack.Models.UserModels.Notification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("MaxshoesBack.Models.UserModels.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            Email = "Employee1@test.pl",
                            IsEmailConfirmed = true,
                            Password = "$2a$11$4mAaQN.8cFI1p2PzdguUiOJMkjrIwPABC4P4S..ly1ZRH1Wntl2V2",
                            Role = "Employee",
                            UserName = "Employee1"
                        },
                        new
                        {
                            Id = "37846734-172e-4149-8cec-6f43d1eb3f61",
                            Email = "Employee2@test.pl",
                            IsEmailConfirmed = true,
                            Password = "$2a$11$2dsPN6uaBQIAQqA8EIekG.niJqdWVlBo3AWD6AzsUz5X2m.Az7KSG",
                            Role = "Employee",
                            UserName = "Employee2"
                        });
                });

            modelBuilder.Entity("MaxshoesBack.Models.UserModels.Notification", b =>
                {
                    b.HasOne("MaxshoesBack.Models.UserModels.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MaxshoesBack.Models.UserModels.User", b =>
                {
                    b.OwnsOne("MaxshoesBack.Models.UserModels.Contact", "Contact", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("ApartmentNumber")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("HouseNumber")
                                .HasColumnType("int");

                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                                    ApartmentNumber = 23,
                                    City = "Czestochowa",
                                    FirstName = "Piter",
                                    HouseNumber = 45,
                                    Id = "46e6a6b5-a0c0-4067-a449-6afe1adb8a38",
                                    LastName = "Blukacz",
                                    PhoneNumber = "666111222",
                                    State = "Polska",
                                    Street = "Zielona",
                                    ZipCode = "42-200"
                                },
                                new
                                {
                                    UserId = "37846734-172e-4149-8cec-6f43d1eb3f61",
                                    ApartmentNumber = 0,
                                    City = "Czestochowa",
                                    FirstName = "Jan",
                                    HouseNumber = 2,
                                    Id = "46aec211-2793-4b6e-af6e-cb1ca269f252",
                                    LastName = "Oko",
                                    PhoneNumber = "666111223",
                                    State = "Polska",
                                    Street = "Liliowa",
                                    ZipCode = "42-202"
                                });
                        });

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("MaxshoesBack.Models.UserModels.User", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
